/**
 * ContextPulse Engine (CPE) Types
 * TypeScript types and interfaces for the ContextPulse Engine
 * which proactively initiates chatbot conversations.
 */

/**
 * Represents the time of day categories for context-aware messaging
 */
export type TimeOfDay = 'morning' | 'afternoon' | 'evening' | 'night';

/**
 * Represents the priority level of a proactive message trigger
 */
export type TriggerPriority = 'low' | 'medium' | 'high' | 'urgent';

/**
 * User activity states that the engine can detect
 */
export type UserActivityState = 'idle' | 'active' | 'returning' | 'new';

/**
 * Context information about the current user session
 */
export interface UserContext {
  /** Unique user identifier */
  userId?: string;
  /** Current time of day */
  timeOfDay: TimeOfDay;
  /** User's activity state */
  activityState: UserActivityState;
  /** Timestamp of last user interaction */
  lastInteractionTime?: Date;
  /** Number of previous chat sessions */
  previousSessionCount: number;
  /** Topics from previous conversations */
  previousTopics?: string[];
  /** User's timezone offset in minutes */
  timezoneOffset?: number;
  /** Whether this is the user's first visit */
  isFirstVisit: boolean;
}

/**
 * Configuration for a proactive message trigger
 */
export interface Trigger {
  /** Unique identifier for the trigger */
  id: string;
  /** Human-readable name for the trigger */
  name: string;
  /** Description of when this trigger should fire */
  description: string;
  /** Priority level of this trigger */
  priority: TriggerPriority;
  /** Function to determine if trigger should fire based on context */
  condition: (context: UserContext) => boolean;
  /** The message or action to take when trigger fires */
  action: TriggerAction;
  /** Cooldown period in milliseconds before trigger can fire again */
  cooldownMs?: number;
  /** Whether this trigger is currently enabled */
  enabled: boolean;
}

/**
 * Action to take when a trigger fires
 */
export interface TriggerAction {
  /** Type of action to take */
  type: 'message' | 'suggestion' | 'notification';
  /** Content of the action */
  content: string;
  /** Optional metadata for the action */
  metadata?: Record<string, unknown>;
}

/**
 * A proactive message generated by the engine
 */
export interface ProactiveMessage {
  /** Unique identifier for this message */
  id: string;
  /** The trigger that generated this message */
  triggerId: string;
  /** Content of the message */
  content: string;
  /** Priority of the message */
  priority: TriggerPriority;
  /** Timestamp when the message was generated */
  generatedAt: Date;
  /** Type of the message */
  type: 'greeting' | 'suggestion' | 'reminder' | 'prompt';
  /** Optional suggested user responses */
  suggestedResponses?: string[];
}

/**
 * Configuration options for the ContextPulse Engine
 */
export interface ContextPulseConfig {
  /** Whether the engine is enabled */
  enabled: boolean;
  /** Maximum number of proactive messages to show per session */
  maxMessagesPerSession: number;
  /** Minimum time between proactive messages in milliseconds */
  minIntervalMs: number;
  /** Custom triggers to add to the engine */
  customTriggers?: Trigger[];
  /** Whether to use AI-generated messages */
  useAIGeneration: boolean;
}

/**
 * State of the ContextPulse Engine
 */
export interface ContextPulseState {
  /** Whether the engine is currently active */
  isActive: boolean;
  /** Current user context */
  currentContext: UserContext | null;
  /** Messages that have been shown in this session */
  shownMessageIds: string[];
  /** Timestamps of trigger firings for cooldown tracking */
  triggerCooldowns: Map<string, Date>;
  /** Number of messages shown in current session */
  messageCount: number;
}

/**
 * Result of evaluating triggers
 */
export interface TriggerEvaluationResult {
  /** Whether any triggers matched */
  matched: boolean;
  /** The matched triggers, sorted by priority */
  matchedTriggers: Trigger[];
  /** The proactive message to display, if any */
  message?: ProactiveMessage;
}
